### ISSUE TITLE
Unable to load the profile error

### ISSUE THREAD

**Issue by HonestAbe7** [j-fbriere/squawker#159]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.6.1

### Steps to reproduce the bug

Install and imported my subscriptions. Then tried to refresh with nothing. So I went to one subscription or person and tapped and got that error message.

### Expected behavior

Expected to see the latest Twitter feeds

### Actual behavior

![Screenshot_20240116-132944](https://github.com/j-fbriere/squawker/assets/88217236/ae1784dd-37d6-4135-baef-5dff23f5f6b4)

### Screenshots/Screen recordings

Sorry but I don't know what else to post other than the error page.

### Logs

Not really a crash

### Affected Android/Custom ROM version

Android 10

### Affected device model

LG355DL

**Comment by j-fbriere** [comment]
Cannot reproduce, sorry.

Profile is working for me.

Question: Do you have the same error for the feed and also the search?

**Comment by HonestAbe7** [comment]
The feed doesn't produce any results for me at all meaning a blank page even when I refresh it.

**Comment by j-fbriere** [comment]
I'm on android 14. I wonder if it's not associated with Android 10.

Do you have both settings activated (enhanced feed and enhanced searches) in Settings / General / X API ?

**Comment by HonestAbe7** [comment]
Also, the Trending section produces the same screenshot error message.

**Comment by j-fbriere** [comment]
ok. so issue #160 it's a duplicate of this issue.

**Comment by HonestAbe7** [comment]
Yes, they are already turned on for me.

**Comment by HonestAbe7** [comment]
OK. Sorry for that. You may close one of them.

**Comment by HonestAbe7** [comment]
Just tried the open source Fritter and I immediately get an error message. So thinking this may be a Twitter thing? Maybe they are restricting guest accounts?

**Comment by j-fbriere** [comment]
The problem with fritter is another type of problem which is indeed related to Twitter/X. 
But Squawker (which is a fork of Fritter) has already resolved this kind of problem. 
So here this is another issue.

**Comment by BlanXyz** [comment]
That is an older build which has been fixed since, this issue is a regression introduced in v3.6.1

**Comment by HonestAbe7** [comment]
Not fixed and I have the latest version which is why I am addressing it here BlanXyz.

**Comment by BlanXyz** [comment]
Fixed in more recent squawker versions, this is a new issue just introduced, yes

**Comment by HonestAbe7** [comment]
No. This is not an older build of the app.

**Comment by j-fbriere** [comment]
Found the problem.
This error has nothing to do with the Android version.
This is because it cannot create a Twitter/X guest account and that there is none already present (maybe there was an uninstall of the app prior to installing the most recent version, then guest accounts are lost).

Why the Twitter/X guest account failed? 
Some possibilities are:
- You are located on a forbidden IP address.
- You are using a VPN that Twitter/X is blocking.
- A Twitter/X guest account was already created sooner today and then swapped by an uninstall. There can be only one Twitter/X guest account creation per day per location.

I will fix the error message.

For your problem, just wait 24 hours before using Squawker, then it should work.
Alternatively today you can change the location (another IP address) and try Squawker. It should work.

**Comment by HonestAbe7** [comment]
Great! I will try again tomorrow!

**Comment by BlanXyz** [comment]
> Found the problem.
> This error has nothing to do with the Android version.
> This is because Squawker cannot create a Twitter/X guest account and that there is none already present in its data (maybe there was an uninstall of the app prior to installing this version, then all Twitter/X guest accounts that were present in the Squawker data are lost).
> 
> Why the Twitter/X guest account failed? 
> Some possibilities are:
> - You are located on a forbidden IP address.
> - You are using a VPN that Twitter/X is blocking.
> - A Twitter/X guest account was already created sooner today and then swapped by an uninstall. There can be only one Twitter/X guest account creation per day per location.
> 
> I will fix the error message.
> 
> For your problem, just wait 24 hours before using Squawker, then it should work.
> Alternatively today you can change the location (another IP address) and try Squawker. It should work.

Yes that was the problem here, Reinstalled several times to test the font bug but thought this was a different error because it never showed the account creation failure logs like usual. Tested from new ip and all is good 👍🏻

**Comment by j-fbriere** [comment]
The next version will add the feature to also export/import the Twitter/X guest accounts.
So when testing by uninstalling/installing the app, simply not forget to export before uninstalling then import after installing, the Twitter/X guest accounts.

**Comment by nooraibk** [comment]
> Found the problem. This error has nothing to do with the Android version. This is because Squawker cannot create a Twitter/X guest account and that there is none already present in its data (maybe there was an uninstall of the app prior to installing this version, then all Twitter/X guest accounts that were present in the Squawker data are lost).
> 
> Why the Twitter/X guest account failed? Some possibilities are:
> 
>     * You are located on a forbidden IP address.
> 
>     * You are using a VPN that Twitter/X is blocking.
> 
>     * A Twitter/X guest account was already created sooner today and then swapped by an uninstall. There can be only one Twitter/X guest account creation per day per location.
> 
> 
> I will fix the error message.
> 
> For your problem, just wait 24 hours before using Squawker, then it should work. Alternatively today you can change the location (another IP address) and try Squawker. It should work.

Installed app yesterday with version 3.6.0. But, before installing 3.6.1, I cleared the app storage (as you said "swapped by an uninstall). Hence previous data got cleared. 
I got my reason cleared but I was also having issue creating guest account with the previous release. Maybe if there is a list of countries with prohibited guest accounts, then it will make it more clear.

**Comment by HonestAbe7** [comment]
This is solved with the new version 3.6.2 that just came out.

**Comment by HonestAbe7** [comment]
Just got this trying to scroll through my feed and got this.

![Screenshot_20240124-140836](https://github.com/j-fbriere/squawker/assets/88217236/1f51902c-e36f-458f-a49e-c3c13d93e964)

**Comment by HonestAbe7** [comment]
Solved! I was blocking twitter by mistake.
