### ISSUE TITLE
v3.7.0 freeze

### ISSUE THREAD

**Issue by zer0fl0w** [j-fbriere/squawker#194]
behavior like mentioned here -> https://github.com/j-fbriere/squawker/issues/192#issuecomment-1935339723

v3.7.0 needs clean install.

but still had this error again. the whole ui freezes. even after fc/clear cache it wont react nor show anything.

cant pull any logs or so, because i have to clear data to get app working again.

sorry i cant provide any further details for now.

**Comment by sh-msh** [comment]
Had the same behaviour after upgrading to 3.7.0.
Deleted cache and data and imported my data from an earlier export. Added newly created X account. Works for now.

**Comment by zer0fl0w** [comment]
i had this scenario again after the first time while adding some subscriptions.

lets see. maybe it wont happen again. wait if there will be more feedback/reports.

**Comment by thedavemiester** [comment]
Me too

**Comment by tadcrazio** [comment]
I had the same issue here, Android 14 pixel 8 pro. 
Upon fresh installation the app was completely frozen cannot navigate anywhere. installed it in a workspace on my phone and it works.. Tried again in my main area , thought maybe it was automatically importing settings or something.. it just worked. ¯\_(ツ)_/¯

**Comment by autogris** [comment]
I have the same issue but cannot access export menu to backup and do a fresh install due to complete freeze (freeze occurs few seconds after opening, not enough time to do an export data)

**Comment by bel57** [comment]
Same. Added account and subscriptions. Now even after clearing cache and force closing, on launch the app instantly freezes.

**Comment by Saroumane** [comment]
Same behavior with 3.7.1

**Comment by taraletti** [comment]
Same behavior on 3.7.0, just updated to 3.7.1 and freezes too (android 8)

**Comment by j-fbriere** [comment]
It happened to me once yesterday with the last version (don't know why yet). 
I closed it and launched it again with no problem. Also I'm on Android 14.

Does it happen all the time or intermittently (like me)?

**Comment by bel57** [comment]
All the time. Android 13, it's freezing on launch. Black screen, can't do anything.

**Comment by zer0fl0w** [comment]
you have to clear app data, not cache.
then it will start and you can add an account and start configuring the app.

i started the thread because i had this hardfreeze _after_ the first "normal" 3.6.5 to 3.7.x conversion bug where you have to start clean.

i could not reproduce it since then tho. it works fine for me until further notice (:

thanks again jean.

**Comment by Saroumane** [comment]
I wanted  to avoid "Clear app data" to avoid losing all settings. Unfortunately android prevents downgrading to 3.6.5 (I wanted to backup settings with 3.6.5, then do a clean install of 3.7.x and restore settings.

By the way, an idea : to avoid this situation it could be nice if an app (before upgrading to a new version) would automatically offer the possibility to backup its settings/data in an external directory.

**Comment by bel57** [comment]
Still, same. Wipe app data. Launch, login with my credentials and 2FA. I import the accounts I follow (~950), then when exiting settings the app start freezing. Force closing, wipe cache, relaunch, freeze.

**Comment by j-fbriere** [comment]
@bel57 Question: When you imported your ~950 subscriptions, did you wait till the message at the bottom appears that the data import was successful before exiting the settings?

**Comment by bel57** [comment]
Yes, I wait long enough till it finishes everything, I get the success message. Then I get back to home page and it gets stuck. Every. Time.
I cleared all data and it's happening again, let me know if there's a way to get the logs

**Comment by thedavemiester** [comment]
I'm on Android 13 and experience the same. 3.7.0 froze almost immediately after import. 3.7.1 worked great for a short period but on reopening froze again

**Comment by zer0fl0w** [comment]
i could just trigger the bug again too by manually removing some accounts in subscriptions tab.

also i can confirm restoring backups from 3.7.x in 3.7.x only partially works. only main settings get restored.

subscriptions wont restore for me although they are in the json. i looked at the json in editor. maybe some format change or so.

**Comment by zxhdmx** [comment]
me too
When I'm searching for something.it will got stuck

**Comment by j-fbriere** [comment]
> subscriptions wont restore for me although they are in the json.
@zer0fl0w Are you talking about subscriptions or searchSubscriptions in your json that is not imported?

**Comment by zer0fl0w** [comment]
the profiles i "follow" under subscriptions tab.

**Comment by j-fbriere** [comment]
> also i can confirm restoring backups from 3.7.x in 3.7.x only partially works. only main settings get restored.

This is strange because I cannot reproduce it. 
What I did:
- Exported the subscriptions
- Removed some subscriptions
- Imported the file
- The removed subscriptions are back

**Comment by zer0fl0w** [comment]
i only tested full backups, not subs only.

**Comment by Saroumane** [comment]
I

> > also i can confirm restoring backups from 3.7.x in 3.7.x only partially works. only main settings get restored.
> 
> This is strange because I cannot reproduce it. What I did:
> 
> * Exported the subscriptions
> * Removed some subscriptions
> * Imported the file
> * The removed subscriptions are back

I reproduce this problem.

- I finally completely uninstalled squawker and did a clean install of 3.7.2
- Then imported json settings made with 3.6.5 : subscriptions are restored.
- Then exported settingd in a new json.
- Then, after a new freeze, uninstalled + clean installed 3.7.2
- Then imported json setting (made with 3.7.2) : subscriptions are not restored in squawker. (But they are in the new json file, I checked)

**Comment by j-fbriere** [comment]
@zer0fl0w, @bel57, @thedavemiester, @Saroumane The version [v3.7.2](https://github.com/j-fbriere/squawker/releases/tag/v3.7.2) should fix the issue of import.

**Comment by taraletti** [comment]
With 3.7.2 it's solved for me

**Comment by bel57** [comment]
Not fixed for me. Login and import are successful but still the same behavior, freezing on the first tab which should show the timeline. Yes I've cleared app cache and data after updating version. Tried uninstalling restarting, reinstalling, same.
![Screenshot_20240211-174902](https://github.com/j-fbriere/squawker/assets/10614811/015f55c4-5468-4404-a0ce-34cbb15f773a)
![Screenshot_20240211-174653](https://github.com/j-fbriere/squawker/assets/10614811/5126c29e-6ce3-455f-8c18-2903a947e2d3)

**Comment by zer0fl0w** [comment]
i think you follow just to much.
try setting up without import of subscriptions.
then see if it generally works by adding only some subs manually, like 10 or 20.

**Comment by bel57** [comment]
The dev tagged me so I assumed it was fixed. Thoughts on followings limit? The app imports those just fine. But it can't handle displaying the timeline after that..

**Comment by j-fbriere** [comment]
ok so the import works or not ?

**Comment by j-fbriere** [comment]
After some analysis I think I know the problem.

There is a rate limit imposed by Twitter/X. It varies depending of the type of Twitter/X API request.
Some types of requests, like the tweets of a profile, have a limit of 150 requests per 15 minutes.
Other types of requests, like the one used for the feed, have a limit of only 50 requests per 15 minutes.

There is also another limitation imposed by Twitter/X, which is the maximum size of each query is 512 characters.
A Twitter/X API request for a feed with 3 subs has a query that looks like the following:
`from:caitoz OR from:Aaaronjmate OR from:ggreenwald`
So if there are many subs in the feed, it must be separated in n requests, each request containing a query of a group of subs up to 512 characters.
I have ~ 50 subs and it executes 4 requests each time the feed is opened or refreshed.
So with ~ 950 subs, the feed executes ~ 75 requests, which is already over the rate limit (50).

Maybe the solution is to create groups with about 100 subs per group?

**Comment by bel57** [comment]
Interesting. Would be great if the app could work with the API limit and offer to pull data according to the rate instead of trying all and freezing. Also instead of having to manually create groups/manually add followings, could the app extract the followings (~950) and allow the user to pick which ones to import?
Maybe I missed something but if you tell me max 100 subs then I'll pick 100 out of 950. Though decision but better than nothing.

**Comment by fgloblek** [comment]
I experienced the freeze issue after upgrading from 3.6.5 to 3.7.1, but
3.7.2 solved the problem completely, no clean install needed. Thank you.

**Comment by j-fbriere** [comment]
> Maybe I missed something but if you tell me max 100 subs then I'll pick 100 out of 950. 

No I meant 100 subs max per group. For 950 subs it means 10 groups (last one with 50 subs).

**Comment by Waredane** [comment]
Hi, to unfreeze the application you must cut off its internet access. to make a backup for example.

**Comment by thomascrisan** [comment]
I am having the problem with version 3.7.2 when I go to the Feed screen.  With version 3.6.5, the Feed screen often displays "Opps! Something when wrong..." because of "Rate limit exceeded".  With version 3.7.2, the application just freezes.

**Comment by j-fbriere** [comment]
@thomascrisan Questions:
- How many subs do you have?
- Do you have specified a regular account (in Settings / Account)?

**Comment by j-fbriere** [comment]
@bel57 Version [v3.7.3](https://github.com/j-fbriere/squawker/releases/tag/v3.7.3) improved the feed requests. You might be able to load the 950 subs.

**Comment by j-fbriere** [comment]
Version [v3.7.3](https://github.com/j-fbriere/squawker/releases/tag/v3.7.3) should fix the issue of freezing.

**Comment by bel57** [comment]
Oh wow, excellent job! It just worked updating without any cache or appdata clearing.
Gotta admit it took a solid 20 seconds to load but hey, it's there :)
Is it a workaround or do I have to expect some rates/toast messages about refreshing limitation?
Also if I understand correctly, the timeline is read only, can't interact at all?

**Comment by j-fbriere** [comment]
>Is it a workaround

It is a different strategy to execute the Twitter/X requests. Instead of executing all the needed Twitter/X requests in parallel, there is now a mix of sequential execution and parallel execution of Twitter/X requests.

> do I have to expect some rates/toast messages about refreshing limitation?

Yes the rate limits are imposed by Twitter/X, so no change there. 50 per 15 min.
In the case of ~950 subs, which executes ~45 requests, it means that it is better to wait 15 minutes before refreshing.

> Also if I understand correctly, the timeline is read only, can't interact at all?

It's read only.
